#When loading plugins ignore files that don't end with .jar
#Default: false
IgnoreNonJarPlugins: true

#The user agent used to make web requests
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

#A list of plugins which should be ignored by batch actions
#Default: [PluginManager]
IgnoredPlugins:
  - PluginManager

#Check for PluginManager updates on startup
#Default: true
CheckForUpdates: true

#Automatically download the latest PluginManager version
#Default: true
AutoUpdate: true

#Hide the PluginManager commands from a player if he/she does not have permission for it
#Default: false
HideNoPermissionCommands: true

#Automatically reload the updated plugins
#default: false
AutoReloadUpdated: false

#Allow the use of batch actions
#Default: true
AllowBatchActions: true